codecov:
  token: 87a3740b-8c16-437d-a0bf-cf5661655747
  branch: stable

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
